version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=elearningdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Jiejie87

  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn final.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DB_NAME=elearningdb
      - DB_USER=postgres
      - DB_PASSWORD=Jiejie87
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=165.245.176.218,localhost,127.0.0.1
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: