# Generated by Django 5.2.7 on 2026-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_remove_user_status_update_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_update',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
